name: ci for simple go app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push to docker hub for release
        run: |
          docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.TOKEN }}
          docker compose -f docker-compose.live.yaml build
          docker compose -f docker-compose.live.yaml push || true
